<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>GanttChartColour.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="GanttChartColour.ico" />
  </ItemGroup>

</Project>
